from app.routes.user_auth_routes import auth_bp
from app.routes.blood_bank_routes import blood_bank_bp
from app.routes.hospital_routes import hospital_bp
from app.routes.blood_group_routes import blood_group_bp
from app.routes.donor_routes import donor_bp
from app.routes.supply_routes import supply_bp
from app.routes.blood_request_routes import blood_request_bp
from app.routes.blood_transport_routes import blood_transport_bp
from app.routes.blood_fridge_routes import blood_fridge_bp
from app.routes.transport_sensor_routes import transport_sensor_bp
from app.routes.blood_inventory_routes import blood_inventory_bp
from app.routes.user_roles_routes import user_role_bp
from app.routes.blood_donation_center_routes import centers_bp